export const styles = {
  hoverStyle: {
    color: "#ffffff",
    textAlign: 'center',
    position: 'relative',
    margin: 0,
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    background: 'rgb(50,50,50)', /* for IE */
    background: 'rgba(50,50,50,0.8)',
    opacity: 1,
    transition: 'opacity .3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 1,
    zIndex: 1,
  },
  inactiveStyle: {
    color: "#ffffff",
    textAlign: 'center',
    position: 'relative',
    margin: 0,
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    background: 'rgb(50,50,50)', /* for IE */
    background: 'rgba(50,50,50,0.8)',
    opacity: 1,
    transition: 'opacity .3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 1,
    zIndex: 1,
  }
}
